server:
  port: 9001

spring:
  application:
    name: oauth-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: toor
    url: jdbc:postgresql://localhost:5432/auth-user

oauth:
  issuer-url: http://127.0.0.1:9001
  default-username: administrator
  default-password: administrator
  default-email: admin@example.com
  client-secret: the_secret


